# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
data = {
    'evolution': [0, 1, 2, 3],
    'hp': [45, 39, 44, 45],
    'name': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
    'pokedex': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
    'type': ['grass', 'fire', 'water', 'bug']
}

### Step 3. Assign it to a variable called pokemon

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   evolution  hp        name     pokedex   type
0          0  45     Ivysaur   Bulbasaur  grass
1          1  39  Charmeleon  Charmander   fire
2          2  44   Wartortle    Squirtle  water
3          3  45     Metapod    Caterpie    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [6]:
df = df[['name', 'type', 'hp', 'evolution', 'pokedex']]
df

         name   type  hp  evolution     pokedex
0     Ivysaur  grass  45          0   Bulbasaur
1  Charmeleon   fire  39          1  Charmander
2   Wartortle  water  44          2    Squirtle
3     Metapod    bug  45          3    Caterpie

### Step 5. Add another column called place, and insert what you have in mind.

In [ ]:
df['place'] = ['park', 'forest', 'cave', 'city']

### Step 6. Present the type of each column

In [8]:
df.dtypes

name         object
type         object
hp            int64
evolution     int64
pokedex      object
dtype: object

### BONUS: Create your own question and answer it.